const users = [
  { id: 1, followed: true, fullName: 'Emma Johnson', about: 'Traveler and foodie', location: { country: 'Canada', city: 'Toronto' }, photoUrl: '' },
  { id: 2, followed: false, fullName: 'Lucas Müller', about: 'Frontend developer', location: { country: 'Germany', city: 'Berlin' }, photoUrl: '' },
  { id: 3, followed: true, fullName: 'Aiko Tanaka', about: 'Nature photographer', location: { country: 'Japan', city: 'Osaka' }, photoUrl: '' },
  { id: 4, followed: false, fullName: 'Mateo García', about: 'Cycling enthusiast', location: { country: 'Spain', city: 'Barcelona' }, photoUrl: '' },
  { id: 5, followed: true, fullName: 'Lina Kovalenko', about: 'UX designer and cat lover', location: { country: 'Ukraine', city: 'Lviv' }, photoUrl: '' },
  { id: 6, followed: false, fullName: 'James Smith', about: 'Enjoys cooking and hiking', location: { country: 'USA', city: 'Seattle' }, photoUrl: '' },
  { id: 7, followed: true, fullName: 'Chiara Rossi', about: 'Architecture student', location: { country: 'Italy', city: 'Milan' }, photoUrl: '' },
  { id: 8, followed: false, fullName: 'Pierre Dubois', about: 'Coffee addict and tech geek', location: { country: 'France', city: 'Lyon' }, photoUrl: '' },
  { id: 9, followed: true, fullName: 'Noura El-Amin', about: 'Digital artist and gamer', location: { country: 'Egypt', city: 'Cairo' }, photoUrl: '' },
  { id: 10, followed: true, fullName: 'Igor Petrov', about: 'History buff and writer', location: { country: 'Russia', city: 'Moscow' }, photoUrl: '' },
  { id: 11, followed: false, fullName: 'Marta Nowak', about: 'Fitness and health coach', location: { country: 'Poland', city: 'Warsaw' }, photoUrl: '' },
  { id: 12, followed: true, fullName: 'Andreas Jensen', about: 'Data analyst and music lover', location: { country: 'Denmark', city: 'Copenhagen' }, photoUrl: '' },
  { id: 13, followed: false, fullName: 'Isabella Silva', about: 'Yoga and wellness enthusiast', location: { country: 'Brazil', city: 'São Paulo' }, photoUrl: '' },
  { id: 14, followed: true, fullName: 'Ali Reza', about: 'Backend dev and chess fan', location: { country: 'Iran', city: 'Tehran' }, photoUrl: '' },
  { id: 15, followed: false, fullName: 'Elena Georgieva', about: 'Books and tea person', location: { country: 'Bulgaria', city: 'Sofia' }, photoUrl: '' },
  { id: 16, followed: true, fullName: 'John Miller', about: 'Car mechanic and vlogger', location: { country: 'USA', city: 'Chicago' }, photoUrl: '' },
  { id: 17, followed: false, fullName: 'Sophie Dubois', about: 'Fashion blogger', location: { country: 'France', city: 'Paris' }, photoUrl: '' },
  { id: 18, followed: true, fullName: 'Ahmed Hassan', about: 'Startup founder and mentor', location: { country: 'UAE', city: 'Dubai' }, photoUrl: '' },
  { id: 19, followed: false, fullName: 'Yuki Nakamura', about: 'Anime fan and developer', location: { country: 'Japan', city: 'Kyoto' }, photoUrl: '' },
  { id: 20, followed: true, fullName: 'Petra Novak', about: 'Journalist and activist', location: { country: 'Czech Republic', city: 'Prague' }, photoUrl: '' },
  { id: 21, followed: false, fullName: 'Alex Kim', about: 'Guitarist and sound engineer', location: { country: 'South Korea', city: 'Seoul' }, photoUrl: '' },
  { id: 22, followed: true, fullName: 'Daniela Almeida', about: 'Graphic designer', location: { country: 'Portugal', city: 'Lisbon' }, photoUrl: '' },
  { id: 23, followed: true, fullName: 'Tomasz Zielinski', about: 'Craft beer lover', location: { country: 'Poland', city: 'Krakow' }, photoUrl: '' },
  { id: 24, followed: false, fullName: 'Natalie Berg', about: 'Marketing specialist', location: { country: 'Sweden', city: 'Stockholm' }, photoUrl: '' },
  { id: 25, followed: true, fullName: 'Omar Farouk', about: 'Crypto enthusiast', location: { country: 'Turkey', city: 'Istanbul' }, photoUrl: '' },
  { id: 26, followed: false, fullName: 'Kristina Ivanova', about: 'Painter and gallery curator', location: { country: 'Ukraine', city: 'Odesa' }, photoUrl: '' },
  { id: 27, followed: true, fullName: 'William Brown', about: 'Nature explorer', location: { country: 'Canada', city: 'Vancouver' }, photoUrl: '' },
  { id: 28, followed: false, fullName: 'Sana Kapoor', about: 'Tech reviewer', location: { country: 'India', city: 'Mumbai' }, photoUrl: '' },
  { id: 29, followed: true, fullName: 'Zhang Wei', about: 'Startup CTO', location: { country: 'China', city: 'Shanghai' }, photoUrl: '' },
  { id: 30, followed: false, fullName: 'Greta Maier', about: 'Photographer and climber', location: { country: 'Austria', city: 'Vienna' }, photoUrl: '' },
];

module.exports = users;